### ISSUE TITLE
opening too many connections kill tedious driver

### ISSUE THREAD

**Issue by bergerdenes** [pekim/tedious-connection-pool#15]
When I try to create about 1000 - 2000 connections with the pool, sometimes (not always..) I got the following error log:
connection closing because of error
error: { name: 'ConnectionError',
  message: 'Failed to connect to MACHINENAME:undefined in 15000ms',
  code: 'ETIMEOUT' }

**Comment by ben-page** [comment]
This has nothing to do with tedious-connection-pool. The error is coming from Tedious directly. You should report it there. 

Frankly, I doubt this is a bug at all. I'm guessing that your SQL Server can not create thousands of  new connections within 15 seconds. You could lengthen the timeout in Tedious. But really, why are you opening that many connections? That kind of defeats the benefit of using the a connection pool.
