### ISSUE TITLE
Overriding max doesn't change min

### ISSUE THREAD

**Issue by lloydcotten** [pekim/tedious-connection-pool#16]
If you pass in optional config overrides and include only `max` and `max` is less than the default `min` value, tedious-connection-pool will still establish the default `min` connections.

The default `min` value is 10, so if the `max` value is changed to something like 5, it will still establish 10 connections.

IMO, if the `max` pool size is changed from the default but `min` is not specified (i.e., left at default), then `min` pool size should be adjusted to `Math.min(this.max, poolConfig.min >= 0 ? poolConfig.min : 10)`.

Regardless, I wouldn't expect that the minimum would ever be more than the maximum.

I can provide a PR for this if this is an acceptable change.  Let me know your opinion on this.

**Comment by ben-page** [comment]
I agree. I'd welcome a PR.

**Comment by lloydcotten** [comment]
PR #17 created.
