### ISSUE TITLE
I can't listen the 'done' event

### ISSUE THREAD

**Issue by SergioGeeK7** [pekim/tedious-connection-pool#18]
that is wrong in this code ...

var ConnectionPool = require('tedious-connection-pool'),
    Request = require('tedious').Request;

var poolConfig = {
    min: 10,
    max: 50,
    log: false
};

var connectionConfig = {
  server: 'some',
  userName: 'sa',
  password: 'some.',
  options: {
    database: 'myTest',
    instanceName: 'SQL2012',
    rowCollectionOnDone:true
    //rowCollectionOnRequestCompletion:true
  }
 // port:3308
  /*
  ,options: {
    debug: {
      packet: true,
      data: true,
      payload: true,
      token: false,
      log: true
    },
    database: 'DBName',
    encrypt: true // for Azure users
  }
  */
};

//create the pool
var pool = new ConnectionPool(poolConfig, connectionConfig);

//acquire a connection
pool.acquire(function (err, connection) {
    if (err)
        console.error(err);

    //use the connection as normal
    var request = new Request('SELECT * FROM mytable', function(err, rowCount) {
        if (err)
            console.error(err);

        console.log('rowCount: ' + rowCount);

        //release the connection back to the pool when finished
        connection.release();
    });

    var arr=[];

   // request.on('row', function(columns) {
       // console.log(columns);

     //   arr.push( columns.map(function  (item) {
          //  return {name:item.metadata.colName , value:item.value};      
       // })); 

       // console.log(arr);
       //console.log('value: ' + columns[0].value);
    //});

    request.on('done', function (rowCount, more, rows) { 

        console.log('I am done'); // this don't execute

         var arry = rows.map(function  (item) {
                return {name:item.metadata.colName , value:item.value} 
        });

         var result=[];

         for (var i=0,j=rows.length;i<j;i++){

            result.push( rows[i].map(function  (item) {
                return {
                    name:item.metadata.colName,
                    value:item.value
                };      
            })); 

         }

         console.log(result);

    });

    connection.execSql(request);
});

pool.on('error', function(err) {
    console.error(err);
});

**Comment by ben-page** [comment]
Have you tried listening for the `doneProc` or `doneInProc` events? You should consult the docs for Tedious. You may have to experiment, the docs aren't clear about which events are fired for which function (`execute`, `execSql`, and `execSqlBatch`). This discussion may be helpful to you: https://github.com/pekim/tedious/issues/61

Ultimately, this question is about tedious, not tedious-connection-pool. So please ask further questions over there.

**Comment by SergioGeeK7** [comment]
thank you bro... yeah I will do. and sorry but this repository is more active than tedios . for that I made that question
