### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by NoumanSaleem** [pekim/tedious-connection-pool#19]
Started seeing this exception after the process has been running for a while (v0.3.5)

```json
{"err":{"message":"Cannot call method 'close' of undefined","name":"TypeError","stack":"TypeError: Cannot call method 'close' of undefined\n    at null._onTimeout (/src/node_modules/tedious-connection-pool/lib/connection-pool.js:215:20)\n    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)"},"msg":"Cannot call method 'close' of undefined"}
```

Nothing fancy in the setup:

```javascript
var pool = new ConnectionPool(
    {
      acquireTimeout: 5000
    },
    {
      password: ----,
      server: ---,
      userName: ---,
      options: {
        port: ---,
        database: ---
      }
    }
  );
```

**Comment by ben-page** [comment]
I can't quite reproduce this error, but I think I found the problem. It seems that even if a connection errors out, it can still timeout. Then the timeout handler tries to close a connection that doesn't exist. Will you please test v0.3.6?

**Comment by NoumanSaleem** [comment]
@ben-page sure thing, getting this pushed out and will watch it over the next day.
Thank you!

**Comment by NoumanSaleem** [comment]
@ben-page that did it. Haven't seen any exceptions yet. 
thanks!
