### ISSUE TITLE
drain callback not always invoked

### ISSUE THREAD

**Issue by jdonnerstag** [pekim/tedious-connection-pool#20]
On my laptop I have no MSSQL installed. I use min 2 and max 4. Upon the timeout the 'error' event handler is invoked. In there I'm calling pool.drain(function() { ... }). I can reproduce that the callback does not get called. Trying to determine the reason I figured  connections.length is 2 (as expected), and waiting.length is 1.
In your ConnectionPool.prototype.drain implementation however, while iterating the waiting list, you do not increment the eventCount, which is why in "ended", the callback is never invoked.

pool version: 0.3.6

Juergen

**Comment by ben-page** [comment]
Fixed in 0.3.7.
