### ISSUE TITLE
drain() does not release all (network) resources

### ISSUE THREAD

**Issue by jdonnerstag** [pekim/tedious-connection-pool#21]
Like in the previous issue, I want to test first the behavior with no MSSQL installed. Obviously it is not able to establish a connection, an error gets emitted, and my error handler invokes drain(). My little test does nothing else. Interestingly node.js does not exit for another 5-10 secs after the drain callback has been called. And that is because (network) resources are not yet released. process._activeHandler provide the information.

Juergen

**Comment by ben-page** [comment]
Apologize but I'm out of the country for a couple more weeks. I don't have access or time to look into this. If you would like to submit a pull request, I'll find some time to review in within  a few days.

**Comment by ben-page** [comment]
I'm not sure what _activeHandler is. Maybe you mean _getActiveHandles?

Anyway, in my tests no network resources are left open, but the retry timer (which defaults to 5 seconds) isn't being cleared. Maybe you didn't wait long enough before checking the handlers. They do take a few hundred milliseconds to close.

Anyway, the retry timer is cleared properly in 0.3.7
