### ISSUE TITLE
Cannot call method 'close' of undefined

### ISSUE THREAD

**Issue by leibale** [pekim/tedious-connection-pool#27]
```
Cannot call method 'close' of undefined,

TypeError: Cannot call method 'close' of undefined
    at D:\home\site\wwwroot\node_modules\tedious-connection-pool\lib\connection-pool.js:241:32
```

**Comment by ben-page** [comment]
Please provide example code,so I can reproduce the problem.

**Comment by leibale** [comment]
i don't know when it's happens. i can give you the list of the functions i use: acquire, release. and i think this is happen when there is a lot of connection errors.

**Comment by ben-page** [comment]
Please confirm that you are using the latest version. There was a big with similar symptoms a while back. 

It would be very helpful if you could narrow the problem  down for me. I'll try infer how this could happen, but without an example I'm not likely to figure it out.

The difficulty is that this is likely to be a bug in your code or your code doing something unexpected which is revealing a bug in the connection pool.

Currently, I have a unit test that tests connection errors. And many people (including myself) use the connection pool in production without running into this error.

**Comment by leibale** [comment]
yes, i'm using version 0.3.9.

i can't give you an example because i don't know what's trigger that.

i going to check my code if is doing something unexpected.

my database have a lot of problems (mostly connection errors) and before i didn't have this error. maybe it's because the last update of SQL Server (v12).

and in my debug session of your code it looks like the test not throw error if the pool didn't emitted any error.

**Comment by leibale** [comment]
i will reopen when it's will happen again
